InventoryManagement/InventoryManagement/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using InventoryManagement.Models;
using System.IO;

namespace InventoryManagement.Controllers
{
    public class CompanyController : Controller
    {
        INVENTORYMNGDBEntities INVENTORYMNGDB = new INVENTORYMNGDBEntities();
        MimeTypeMap mimeType = new MimeTypeMap();
        GeneralModels GeneralModels = new GeneralModels();
        // GET: Company
        public ActionResult Index()
        {
            try
            {
                ViewBag.CompanyInfo_result = INVENTORYMNGDB.spGetCompanyInformation(1).ToList();                
            }
            catch { }

            return View();
        }

        public ActionResult BranchOffices()
        {            
            return View();
        }

        public PartialViewResult _InsertUpdateCompany(int CID)
        {
            //CID == CompanyID

            spGetCompanyInformation_Result CompanyInfo_Result = new spGetCompanyInformation_Result();
            var CompanyInfo = INVENTORYMNGDB.spGetCompanyInformation(CID).FirstOrDefault();

            if (CompanyInfo == null)
            { CompanyInfo_Result.companyID = 0; }
            else { CompanyInfo_Result = CompanyInfo; }

            ViewBag.Country_result = INVENTORYMNGDB.spGetCountry().ToList();

            return PartialView("_InsertUpdateCompany", CompanyInfo_Result);
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult _InsertUpdateCompanyInfo(spGetCompanyInformation_Result fileData)
        {
            var CreatedBy = "1";
            var companyID = 0;
            var result = "";

            if (fileData.companyID > 0)
            {
                if (Request.Files.Count > 0)
                {
                    byte[] returnimageBytes = null;
                    string filename = "";
                    string filetype = "";
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        filename = Path.GetFileName(Request.Files[i].FileName);
                        filetype = mimeType.GetMimeType(Path.GetExtension(Request.Files[i].FileName).ToLower().Replace(".", "").Trim());
                        HttpPostedFileBase file = files[i];
                        if (filename != null && filename != "")
                        {
                            returnimageBytes = GeneralModels.ConvertToBytes(file);
                        }
                        else
                        {
                            returnimageBytes = null;
                        }

                        companyID = (int)INVENTORYMNGDB.spCompanyUpdate(fileData.companyID, fileData.countryID, fileData.companyName, 
                            fileData.companyAddress, fileData.companyContact, fileData.companyEmail, fileData.companyPhone, fileData.companyFax,
                            returnimageBytes, int.Parse(CreatedBy)).FirstOrDefault().Value;
                        result = "Updated";
                    }
                }
                else
                {
                    companyID = (int)INVENTORYMNGDB.spCompanyUpdate(fileData.companyID, fileData.countryID, fileData.companyName,
                            fileData.companyAddress, fileData.companyContact, fileData.companyEmail, fileData.companyPhone, fileData.companyFax,
                            null, int.Parse(CreatedBy)).FirstOrDefault().Value;
                    result = "Updated";
                }

            }
            else
            {
                if (Request.Files.Count > 0)
                {
                    byte[] returnimageBytes = null;
                    string filename = "";
                    string filetype = "";
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        filename = Path.GetFileName(Request.Files[i].FileName);
                        filetype = mimeType.GetMimeType(Path.GetExtension(Request.Files[i].FileName).ToLower().Replace(".", "").Trim());
                        HttpPostedFileBase file = files[i];
                        if (filename != null && filename != "")
                        {
                            returnimageBytes = GeneralModels.ConvertToBytes(file);
                        }
                        else
                        {
                            returnimageBytes = null;
                        }

                        companyID = (int)INVENTORYMNGDB.spCompanyInsert(fileData.countryID, fileData.companyName,
                            fileData.companyAddress, fileData.companyContact, fileData.companyEmail, fileData.companyPhone, fileData.companyFax,
                            returnimageBytes, int.Parse(CreatedBy)).FirstOrDefault().Value;
                        result = "Inserted";
                    }
                }
            }
            return Json(new { companyID = companyID, Message = result }, JsonRequestBehavior.AllowGet);
        }

    }
}

InventoryManagement/InventoryManagement/Views/Company/BranchOffices.cshtml
@{
    Layout = null;
}

    <div class="card-body pb-0">
        <div class="row d-flex align-items-stretch">
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                <div class="card bg-light">
                    <div class="card-header text-muted border-bottom-0">
                        United States
                    </div>
                    <div class="card-body pt-0">
                        <div class="row">
                            <div class="col-7">
                                <h2 class="lead"><b>Casa Matriz</b></h2>
                                <p class="text-muted text-sm"><b>Contact: </b> Nicole Pearson</p>
                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                </ul>
                            </div>
                            <div class="col-5 text-center">
                                <img src="~/Content/dist/img/user1-128x128.jpg" alt="user-avatar" class="img-circle img-fluid">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right">
                            <a href="#" class="btn btn-sm bg-teal">
                                <i class="fas fa-comments"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-primary">
                                <i class="fas fa-user"></i> Ver Sucursal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                <div class="card bg-light">
                    <div class="card-header text-muted border-bottom-0">
                        El Salvador
                    </div>
                    <div class="card-body pt-0">
                        <div class="row">
                            <div class="col-7">
                                <h2 class="lead"><b>Metrocentro</b></h2>
                                <p class="text-muted text-sm"><b>Contact: </b> Nicole Pearson</p>
                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                </ul>
                            </div>
                            <div class="col-5 text-center">
                                <img src="~/Content/dist/img/photo2.png" alt="user-avatar" class="img-circle img-fluid">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right">
                            <a href="#" class="btn btn-sm bg-teal">
                                <i class="fas fa-comments"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-primary">
                                <i class="fas fa-user"></i> Ver Sucursal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                <div class="card bg-light">
                    <div class="card-header text-muted border-bottom-0">
                        Guatemala
                    </div>
                    <div class="card-body pt-0">
                        <div class="row">
                            <div class="col-7">
                                <h2 class="lead"><b>Miraflores</b></h2>
                                <p class="text-muted text-sm"><b>Contact: </b> Nicole Pearson</p>
                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                </ul>
                            </div>
                            <div class="col-5 text-center">
                                <img src="~/Content/dist/img/image11.jpg" alt="user-avatar" class="img-circle img-fluid">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-right">
                            <a href="#" class="btn btn-sm bg-teal">
                                <i class="fas fa-comments"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-primary">
                                <i class="fas fa-user"></i> Ver Sucursal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

InventoryManagement/InventoryManagement/Views/Company/_InsertUpdateCompany.cshtml
@model InventoryManagement.Models.spGetCompanyInformation_Result

@{
    var Country = (List<InventoryManagement.Models.spGetCountry_Result>)ViewBag.Country_result;
}

@Html.AntiForgeryToken()
@Html.ValidationSummary(true)

<div class="modal-header">
    @if (Model.companyID == 0)
    {<h4 class="modal-title">Add Company</h4> }
    else
    { <h4 class="modal-title">Edit Company</h4>}

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

@using (Ajax.BeginForm("_InsertUpdateCompanyInfo", "Company", null, new AjaxOptions
{ HttpMethod = "POST", OnSuccess = "SuccessCompany", OnFailure = "FailCompanyPost" },
new { id = "formCompany", @enctype = "multipart/form-data" }))
{
    var filename = "";
    if (Model.companyAvatar != null)
    {
        filename = ".../" + Model.companyAvatar + ViewBag.FileExtension;
    }

    <div class="modal-body">
        <div class="col-lg-12">
            @Html.HiddenFor(m => m.companyID, new { id = "txtCompanyID" })
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Logo</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6" id="FileDiv">
                    <div class="form-group">
                        <div class="input-group" style="width: 100%;">
                            <input type="text" id="inpTextFileCompany" placeholder='@filename' class="form-control form-control-round" disabled="disabled" style="border-radius: 6px 0px 0px 6px; height:36px;width:69%" tabindex="1" />
                            <span class="btn btn-block btn-outline-warning btn-sm" style="padding: 2px 3px 2px 3px; font-size: 15px; line-height: 2.0; border-radius: 5px; height: auto; width: 40%; border-radius: 0px 6px 6px 0px;">
                                <i class="fa fa-paperclip"></i>
                                <span>Select File</span>
                                <input type="file" name="fileCompany" id="fileCompany" accept="application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint,text/plain, application/pdf, image/*" runat="server" CssClass="file" Style="position: absolute; opacity: 0; -ms-filter: 'alpha(opacity=0)'; direction: ltr; cursor: pointer; width: 150px; height: 35px; margin-top: -4px; margin-left: -110px;" onchange="changeFile()" />
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Company Name</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-building"></i></span>
                        </div>
                        @Html.TextBoxFor(m => m.companyName, new { @class = "form-control form-control-sm", @placeholder = "Company Name", @id = "txtCompanyName", required = true })
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Contact</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-id-badge"></i></span>
                        </div>
                        @Html.TextBoxFor(m => m.companyContact, new { @class = "form-control form-control-sm", @placeholder = "Contact", @id = "txtCompanyContact", required = true })
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Email</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                        </div>
                        @Html.TextBoxFor(m => m.companyEmail, new { @class = "form-control form-control-sm", @placeholder = "Email", @id = "txtCompanyEmail", required = true })
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Phone</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                        </div>
                        @Html.TextBoxFor(m => m.companyPhone, new { @class = "form-control form-control-sm", @placeholder = "Phone", @id = "txtCompanyPhone", required = true })
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Fax</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-fax"></i></span>
                        </div>
                        @Html.TextBoxFor(m => m.companyFax, new { @class = "form-control form-control-sm", @placeholder = "Fax", @id = "txtCompanyFax", required = true })
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Country</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-globe"></i></span>
                        </div>
                        @Html.DropDownListFor(m => m.countryID, new SelectList(Country as System.Collections.IEnumerable, "countryID", "countryName"), "Select", new { @class = "form-control select2 addSelect2", Required = true, @id = "ddlCountryCompany", @style = "width:100%;" })
                        @Html.Hidden("txtCountryIDCompany", Model.countryID, new { @id = "txtCountryIDCompany" })
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="margin-bottom: -0.50em">
                <div class="col-lg-3 col-md-3 col-sm-6 form-control-label">
                    <label>Address</label>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-6">
                    <div class="form-group">
                        <div class="input-group">
                            @Html.TextAreaFor(m => m.companyAddress, new { @class = "form-control", @placeholder = "Address", @id = "txtAddress", @rows = 2 })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <hr />
            </div>
        </div>
    </div>
    <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary" id="btnSaveCompany" data-action="Click on save Company">Save changes</button>
    </div>
}

<script>
    $(document).ready(function () {
        //GetBeginArray('modal-default-content');
    });

    function SuccessCompany(data) {
        if (data.Message == 'Updated') {
            AlertNotification("info", "The information was modified successfully!");            
            $('#modal-default-content').empty();
            $('#modal-default').modal('hide');
            location.reload();
        }
        if (data.Message == 'Inserted') {
            AlertNotification("success", "The information was successfully stored!");            
            $('#modal-default-content').empty();
            $('#modal-default').modal('hide');
            location.reload();
        }
        if (data.Message == 'Fail') {
            AlertNotification("error", "Sorry, an error occurred when entering Company information!");            
            $('#modal-default-content').empty();
            $('#modal-default').modal('hide');
        }
    }

    function FailCompanyPost(data) {
        if (data == 'Fail') {
            AlertNotification("error", "Sorry, an error occurred when entering Company information!");   
            $('#modal-default-content').empty();
            $('#modal-default').modal('hide');
        }
    }

    $('#formCompany').submit(function (e) {
        success: (function (data) {
            // e.preventDefault();
            SuccessCompany(data);
            return;
        });
    });

    function changeFile() {
        if ($("#fileCompany")[0].files.length > 0) {
            var cadena = document.getElementById('fileCompany').files[0].name;
            const lastDot = cadena.lastIndexOf('.');
            document.getElementById("inpTextFileCompany").value = '../' + cadena;
            //document.getElementById("txtFileName").value = cadena.substring(0, lastDot);
        }
    };
</script>